---
- hosts: linexos-scheduler01
  tasks:

    - name: Import Bacula key
      apt_key:
        url: https://www.bacula.org/downloads/Bacula-4096-Distribution-Verification-key.asc
        state: present

#    - name: Install apt-transport-https
#      apt:
#        name: apt-transport-https
#        state: present
#        update_cache: yes

    - name: Download Bacula GPG key
      ansible.builtin.get_url:
        url: https://bacula.org/downloads/Bacula-4096-Distribution-Verification-key.asc
        dest: /tmp/Bacula-4096-Distribution-Verification-key.asc

    - name: Add Bacula GPG key
      apt_key:
        file: /tmp/Bacula-4096-Distribution-Verification-key.asc
        state: present

    - name: Add Bacula Repository
      apt_repository:
        repo: 'deb [arch=amd64] https://bacula.org/packages/5bd703346c037/debs/13.0.4 bookworm main'
        filename: 'bacula'
        state: present
        update_cache: yes

    - name: Update apt cache and fix broken installs
      apt:
        update_cache: yes
        force_apt_get: yes
        state: fixed

    - name: Install or update bacula-client
      apt:
        name:
          - bacula-client
          - bacula-console
          - bacula-console-qt
        state: present
        update_cache: yes

    - name: Copy last configuration
      copy:
        remote_src: yes
        src: /etc/ansible/roles/lx_prepare_debian_vm/files/bacula.j2
        dest: /opt/bacula/etc/bacula-fd.conf
    - name: Restart bacula-fd
      service:
          name: bacula-fd
          state: restarted


